package com.any2api.provider;

public enum ProviderCapability {
    CHAT_COMPLETIONS,
    RESPONSES,
    STREAMING,
    REASONING,
    FUNCTION_TOOLS,
    STRUCTURED_OUTPUT,
    IMAGE_INPUT,
    IMAGE_GENERATION,
    IMAGE_EDITING,
    AUDIO_INPUT,
    VIDEO_INPUT,
    VIDEO_GENERATION,
    FILE_INPUT,
    STORED_RESPONSES,
    MODEL_DISCOVERY,
    ACCOUNT_KEEPALIVE,
    REGISTRATION,
    REAUTHENTICATION
}
